#!/usr/bin/php -q
<?php
$mongo = new Mongo();
$db = $mongo->xE;

$name = 'test';
$pidfile = '/var/run/phpd.pid';
$mastersocket = '/tmp/phpDaemon-master-%x.sock';

class xEngine{
	public $name;
	public function __construct($path,$name) {
		$this->name = $name;
		$this->sock = stream_socket_client($path, $errno, $errstr);
		if (!$this->sock) {
			$e = new CouldntConnect;
			$e->path = $path;
			throw $e;
		}
	}
	public function sendPacket($p) {
		fwrite($this->sock,json_encode($p)."\n");
	}
	public function __call($m,$a) {
		$this->sendPacket(array(
					'op' => 'singleCall',
					'appfullname' => 'xEngine-'.$this->name,
					'method' => $m,
					'args' => $a
		));
	}
}
class CouldntConnect extends Exception {}


try {
	$app = new xEngine('unix://'.sprintf($mastersocket, crc32($pidfile)),$name);
}
catch (CouldntConnect $e) {
	exit('Connection failed to '.$e->path.'.');
}

/* sessions */ 
$sessions = $db->selectCollection('sessions');
$sessions->remove();
$sessions->ensureIndex(array('accountId' => 1));

/* accounts */ 
$accounts = $db->selectCollection('accounts');
$accounts->remove();
$accounts->ensureIndex(array('username' => 1),array('unique' => true));
$accounts->ensureIndex(array('email' => 1),array('unique' => true));
$app->saveAccount(array(
				'username' => 'Guest',
				'password' => '',
				'aclgroups' => array('Guests'),
				'acl' => array(),
));
$app->saveAccount(array(
				'username' => 'admin',
				'password' => 'passphrase',
				'aclgroups' => array('Superusers'),
				'acl' => array(),
));

/* aclgroups */ 
$aclgroups = $db->selectCollection('aclgroups');
$aclgroups->remove();
$aclgroups->ensureIndex(array('name' => 1),array('unique' => true));
$app->saveACLgroup(array(
				'name' => 'Superusers',
				'acl' => array('global' => array('all','grant')),
));

/* blocks */ 
$blocks = $db->selectCollection('blocks');
$blocks->remove();
$blocks->ensureIndex(array('name' => 1));
$blocks->ensureIndex(array('lang' => 1, 'path' => 1));
$app->saveBlock(array(
				'name' => 'trololo',
				'template' =>	'Hello world!'
));
$app->saveBlock(array(
				'name' => 'ACP',
				'type' => 'ACP',
				'template' =>	'ACP.',
				'path' => '/ACP'
));
$app->saveBlock(array(
				'name' => 'PageStart',
				'type' => 'PageStart',
				'template' =>	'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<title>{$block->parentNode->title} - xEngine demo</title> 
<link href="/css/jquery-ui-1.8.6.custom.css" rel="stylesheet" type="text/css" /> 
<link href="/css/jquery.contextMenu.css" rel="stylesheet" type="text/css" /> 
<link href="/css/main.css" rel="stylesheet" type="text/css" /> 
<link href="favicon.ico" rel="icon" type="image/x-icon" /> 
<link href="favicon.ico" rel="shortcut icon" type="image/x-icon" /> 
<meta name="description" content="phpDaemon" /> 
<meta name="keywords" content="phpDaemon, php" /> 
{?$libs = "https://ajax.googleapis.com/ajax/libs/"}{?$jqmin = false}
<script src="{$libs}jquery/1.4.3/jquery{$jqmin?".min":""}.js"></script>
<script src="{$libs}jqueryui/1.8.6/jquery-ui{$jqmin?".min":""}.js"></script>
<script src="/js/CP.js" type="text/javascript"></script>
<script src="/js/jquery.keyboard.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/tiny_mce/jquery.tinymce.js"></script>
<script src="/js/jquery.contextMenu.js" type="text/javascript"></script>
</head> 
<body><div class="block" id="{$block->parentNode->_id}">',
));
$app->saveBlock(array(
				'name' => 'PageEnd',
				'type' => 'PageEnd',
				'template' =>	'</div></body></html>',
));
$app->saveBlock(array(
				'name' => 'UserMiniPanel',
				'type' => 'UserMiniPanel',
				'template' =>	'{if $req->account.logged}Hello, <a href="#"><strong>{$req->account.username|escape}</strong></a>!{else}<a href="#">Login</a> or <a href="#">register</a>{/if}',
));
$app->saveBlock(array(
				'name' => 'Footer',
				'type' => 'Footer',
				'template' =>	'<address<s>©</s> Z-IT 2010</address><br />Page took (real time): {getBlock type="Pagetook"}',
));
$app->saveBlock(array(
				'lang' => 'en',
				'path' => '/',
				'title' => 'Main page',
				'template' => '{getBlock name="PageStart"}

{getBlock name="UserMiniPanel"}

{getBlock name="trololo"}

<br /><br />
text in body

{getBlock name="Footer"}

{getBlock name="PageEnd"}
'));

