#!/usr/bin/env php
<?php
include __DIR__.'/../generic.php';

/* accounts */ 
$accounts = $db->selectCollection('accounts');
//$accounts->drop();
$app->saveAccount(array(
				'username' => 'Guest',
				'email' => 'guest@guest.tld',
				'aclgroups' => array('Guests'),
				'acl' => array(),
));
$app->saveAccount(array(
				'username' => 'admin',
				'password' => 'passphrase',
				'email' => 'admin@admin.tld',
				'aclgroups' => array('Superusers', 'Users'),
				'acl' => array(),
));
