#!/usr/bin/env php
<?php
include __DIR__.'/../generic.php';

/* aclgroups */ 
$aclgroups = $db->selectCollection('aclgroups');
$aclgroups->drop();
$aclgroups->ensureIndex(array('name' => 1),array('unique' => true));
$app->saveACLgroup(array(
				'name' => 'Superusers',
				'acl' => array('global' => array('all','grant')),
));
