#!/usr/bin/env php
<?php
include __DIR__.'/../generic.php';

/* aclgroups */ 
$aclgroups = $db->selectCollection('aclgroups');
//$aclgroups->drop();
$app->saveACLgroup(array(
				'name' => 'Superusers',
				'acl' => array('global' => array('all','grant')),
));
