#!/usr/bin/env php
<?php
include __DIR__.'/../generic.php';

/* authtokens */ 
$authtokens = $db->selectCollection('authtokens');
$authtokens->drop();
$authtokens->ensureIndex(array('token' => 1),['unique'=>true]);
