#!/usr/bin/env php
<?php
include __DIR__.'/../generic.php';

/* jobqueue */ 
$jobqueue = $db->selectCollection($name = 'jobqueue');
$jobqueue->drop();
$db->command(['create' => $name, 'capped' => true, 'size' => 1024*1024*10, 'max' => 1024 * 10]);
$jobqueue->ensureIndex(array('status' => 1));
