#!/usr/bin/env php
<?php
include __DIR__.'/../generic.php';

/* jobqueue */ 
$jobqueue = $db->selectCollection('jobqueue');
$jobqueue->drop();
$jobqueue->ensureIndex(array('status' => 1, 'ts' => 1));
