#!/usr/bin/env php
<?php
include __DIR__.'/../generic.php';

/* jobs */ 
$jobs = $db->selectCollection($name = 'jobs');
$jobs->drop();
$jobs->ensureIndex(array('instance' => 1, 'ts' => 1));
$jobs->ensureIndex(array('trickyId' => 1));

