#!/usr/bin/php -q
<?php
include __DIR__.'/../generic.php';

/* outgoingmail */ 
$outgoingmail = $db->selectCollection('outgoingmail');
$outgoingmail->drop();
$outgoingmail->ensureIndex(array('status' => 1));
