#!/usr/bin/env php
<?php

include 'generic.php';

chdir(__DIR__.'/..');

/* blocks */ 
$blocks = $db->selectCollection('blocks');
$find = $blocks->find();
while ($block = $find->getNext()) {
	
	if (isset($block['template'])) {
		file_put_contents('./PackagedThemes/'.$theme.'/blocks/'.$block['name'].'.tpl',$block['template']);
		unset($block['template']);
	}
	unset($block['templatePHP']);
	unset($block['templateBC']);
	unset($block['_id']);
	file_put_contents('./PackagedThemes/'.$theme.'/blocks/'.$block['name'].'.obj',json_encode($block));
}
