#!/usr/bin/python

import sys
import simplejson as enc
import gettext
    
def gettext_json(domain, path, lang = [], indent = False):
    try:
        tr = gettext.translation(domain, path, lang)
        # for unknown reasons, instead of having plural entries like 
        # key: [sg, pl1...]
        # tr._catalog has (key, n): pln, 
        keys = tr._catalog.keys()
        keys.sort()
        ret = {}
        for k in keys:
            v = tr._catalog[k]
            if type(k) is tuple:
                if k[0] not in ret:
                    ret[k[0]] = []
                ret[k[0]].append(v)
            else:
                ret[k] = v
        return enc.dumps(ret, ensure_ascii = True, indent = indent)
    except IOError as (errno, strerror):
			print "I/O error({0}): {1}".format(errno, strerror)	
        
print gettext_json(sys.argv[1],sys.argv[2],[sys.argv[3]], True)
