#!/usr/bin/php -q
<?php
include 'generic.php';

shell_exec(__DIR__.'/ImportBlocks');

shell_exec(__DIR__.'/BuildLocales');

foreach (glob(__DIR__.'/DBM/*') as $path) {
	passthru(escapeshellarg($path));
}
