#!/usr/bin/php -q
<?php
include 'generic.php';

$pid = pcntl_fork();
if ($pid == -1) {
     die('could not fork');
} else if ($pid) {
     exit;
} else {
		$sid = posix_setsid();
		if ($sid < 0) {
			exit('setsid() failed');
		}
}
if (is_callable('setproctitle')) {
	setproctitle('SendmailDaemon');
}
echo "Forked.\n";
$outgoingmail = $db->selectCollection('outgoingmail');
while (true) {
	$mail = $outgoingmail->findOne(array('status' => 'vacant'));
	if (!$mail) {
		sleep(1);
		continue;
	}
	try {
		$outgoingmail->update(array('_id' => $mail['_id']), array('$set' => array('status' => 'acquired')), array('safe' => true));
	} catch (MongoCursorException $e) {
		continue;
	}
	$success = call_user_func_array('mail', $mail['args']);
	$outgoingmail->update(array('_id' => $mail['_id']), array('$set' => array('status' => $success ? 'succeed' : 'failed')), array('safe' => true));
}
