#!/usr/bin/php -q
<?php
include 'generic.php';

$outgoingmail = $db->selectCollection('outgoingmail');
while (true) {
	$mail = $outgoingmail->findOne(array('status' => 'vacant'));
	if (!$mail) {
		sleep(1);
		continue;
	}
	try {
		$outgoingmail->update(array('_id' => $mail['_id']), array('$set' => array('status' => 'acquired')), array('safe' => true));
	} catch (MongoCursorException $e) {
		continue;
	}
	$success = call_user_func_array('mail', $mail['args']);
	$outgoingmail->update(array('_id' => $mail['_id']), array('$set' => array('status' => $success ? 'succeed' : 'failed')));
}
